const artists = [
  {
    id: 1,
    name: "Aroha Te",
    avatar: "https://images.unsplash.com/photo-1615538786254-ad8b50de17dc?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    place: "Aotearoa",
    bio: "Aroha Te è un'artista maori che trae ispirazione dalla natura e dalla cultura tradizionale della Nuova Zelanda. Le sue opere riflettono un profondo rispetto per l'ambiente e la spiritualità maori.",
    date: "Gennaio 2025",
    materials: "inchiostro, carta ruvida",
    status: "certificato",
    instagram: "https://www.instagram.com/",
    website: "https://it.wikipedia.org/wiki/Maori",
    email: "#",
    twitter: "https://it.wikipedia.org/wiki/Pagina_principale",
    cover: "https://images.unsplash.com/photo-1560697529-7236591c0066?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 2,
    name: "Rongo Pikiatua",
    avatar: "https://images.unsplash.com/photo-1529758146491-1e11fd721f77?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    place: "Rotorua",
    bio: "Rongo Pikiatua lavora tra pittura e scultura, esplorando l'identità e la memoria culturale della sua terra. Le sue opere utilizzano materiali naturali e pigmenti locali.",
    date: "Febbraio 2025",
    materials: "pigmenti naturali, carta biologica",
    status: "certificato",
    instagram: "https://www.instagram.com/",
    website: "#",
    email: "#",
    twitter: "https://it.wikipedia.org/wiki/Pagina_principale",
    cover: "https://images.unsplash.com/photo-1560697529-7236591c0066?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 3,
    name: "Teika Moanaroa",
    avatar: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    place: "Wellington",
    bio: "Teika Moanaroa crea illustrazioni e stampe ispirate ai miti maori, fondendo stili grafici moderni con simbolismi tradizionali.",
    date: "Marzo 2025",
    materials: "Acquerello, Carta Riciclata",
    status: "certificato",
    instagram: "https://www.instagram.com/",
    website: "https://it.wikipedia.org/wiki/Pagina_principale",
    email: "#",
    twitter: "#",
    cover: "https://images.unsplash.com/photo-1560697529-7236591c0066?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 4,
    name: "Te Rerehua Wikitōria",
    avatar: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?q=80&w=989&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    place: "Tāmaki Makaurau (Auckland)",
    bio: "Te Rerehua Wikitōria lavora nel campo dell'arte digitale e video arte, affrontando temi legati alla decolonizzazione e al linguaggio visivo maori contemporaneo.",
    date: "Aprile 2025",
    materials: "Pennarelli & carta liscia",
    status: "certificato",
    instagram: "https://www.instagram.com/",
    website: "#",
    email: "#",
    twitter: "https://it.wikipedia.org/wiki/Pagina_principale",
    cover: "https://images.unsplash.com/photo-1560697529-7236591c0066?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 5,
    name: "Mereana Kauri",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    place: "Northland",
    bio: "Mereana Kauri si dedica alla fotografia documentaristica, catturando paesaggi e ritratti che raccontano la resilienza e la bellezza delle comunità indigene.",
    date: "Maggio 2025",
    materials: "china su carta fotografica",
    status: "/",
    instagram: "https://www.instagram.com/",
    website: "https://it.wikipedia.org/wiki/Pagina_principale",
    email: "https://it.wikipedia.org/wiki/Pagina_principale",
    twitter: "#",
    cover: "https://images.unsplash.com/photo-1560697529-7236591c0066?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 6,
    name: "Hinemoana Raukura",
    avatar: "https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    place: "Bay of Plenty",
    bio: "Hinemoana Raukura combina tessitura tradizionale e installazioni contemporanee per raccontare storie tramandate oralmente nelle famiglie maori.",
    date: "Giugno 2025",
    materials: "inchiostro su tessuto",
    status: "certificato",
    instagram: "#",
    website: "https://it.wikipedia.org/wiki/Pagina_principale",
    email: "https://it.wikipedia.org/wiki/Pagina_principale",
    twitter: "#",
    cover: "https://images.unsplash.com/photo-1560697529-7236591c0066?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

export default artists;
