const artworks = [
    {
      id: "AUT25-001",
      title: "Te Manu o te Rangi",
      artist: "Aroha Te Ao",
      status: "available",
      price: 45,
      owner: "Certificato Originale",
      collection: "Autunno 2025",
      description: "'L'uccello del cielo' in maori, evocando un volatile sacro, forse un kererū o un falco nativo.",
      image: "https://images.unsplash.com/photo-1747945872974-4d814f768def?q=80&w=963&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      sealDate: "12 Settembre 2025",
      materials: "Cartoncino - dipinta a mano",
      dimensions: "63 mm x 88 mm",
      edition: "1/1 - Pezzo Unico",
      tags: ["maori", "uccelli", "sacro", "natura", "tradizionale"],
      likes: 89,
      views: 1245,
    },
    {
      id: "AUT25-007",
      title: "Moana Kōtare",
      artist: "Rongo Pikiatua",
      status: "sold",
      price: 45,
      owner: "Certificato Originale",
      collection: "Autunno 2025",
      description: "Martin pescatore dell'oceano — un tributo all'avifauna costiera delle isole del Pacifico.",
      image: "https://images.unsplash.com/photo-1709805902570-fcb5c9d99d5e?q=80&w=989&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      sealDate: "18 Settembre 2025",
      materials: "Cartoncino - dipinta a mano",
      dimensions: "63 mm x 88 mm",
      edition: "1/1 - Pezzo Unico",
      tags: ["oceano", "martin pescatore", "pacifico", "costiero", "blu"],
      likes: 156,
      views: 2103,
    },
    {
      id: "AUT25-012",
      title: "Whakarere Kārearea",
      artist: "Teika Moanaroa",
      price: 45,
      owner: "Certificato Originale",
      collection: "Autunno 2025",
      description: "Il volo del falco della Nuova Zelanda — un'immagine dinamica del kārearea, il falco nativo Aotearoa.",
      status: "sold",
      image: "https://images.unsplash.com/photo-1709802191476-5a417cb6b971?q=80&w=950&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      sealDate: "22 Settembre 2025",
      materials: "Cartoncino - dipinta a mano",
      dimensions: "63 mm x 88 mm",
      edition: "1/1 - Pezzo Unico",
      tags: ["falco", "volo", "dinamico", "nuova zelanda", "nativo"],
      likes: 203,
      views: 1876,
    },
    {
      id: "AUT25-018",
      title: "Tūī Karanga",
      artist: "Te Rerehua Wikitōria",
      price: 45,
      owner: "Certificato Originale",
      collection: "Autunno 2025",
      description: "Il canto del tūī — uccello iconico noto per il suo verso armonioso e il piumaggio iridescente.",
      status: "available",
      image: "https://images.unsplash.com/photo-1709235175253-d6c1892e1d39?q=80&w=997&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      sealDate: "25 Settembre 2025",
      materials: "Cartoncino - dipinta a mano",
      dimensions: "63 mm x 88 mm",
      edition: "1/1 - Pezzo Unico",
      tags: ["tui", "canto", "armonioso", "iridescente", "iconico"],
      likes: 134,
      views: 1654,
    },
    {
      id: "SPR25-001",
      title: "Piko o te Māra",
      artist: "Mereana Kauri",
      status: "sold",
      price: 45,
      owner: "Certificato Originale",
      collection: "Estate 2025",
      description: "Spirali del giardino — un riferimento alle felci arrotolate (piko) e alla simbologia della nuova vita.",
      image: "https://images.unsplash.com/photo-1515096788709-a3cf4ce0a4a6?q=80&w=3158&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      sealDate: "5 Marzo 2025",
      materials: "Cartoncino - dipinta a mano",
      dimensions: "63 mm x 88 mm",
      edition: "1/1 - Pezzo Unico",
      tags: ["spirali", "felci", "giardino", "nuova vita", "verde"],
      likes: 178,
      views: 2234,
    },
    {
      id: "SPR25-007",
      title: "Ngā Rau o Tane",
      artist: "Teika Moanaroa",
      status: "sold",
      price: 45,
      owner: "Certificato Originale",
      collection: "Estate 2025",
      description: "Le foglie di Tāne — Tāne Mahuta è il dio della foresta nella mitologia maori, padre di tutte le piante.",
      image: "https://images.unsplash.com/photo-1530903677198-7c9f3577a63e?q=80&w=1552&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      sealDate: "15 Marzo 2025",
      materials: "Cartoncino - dipinta a mano",
      dimensions: "63 mm x 88 mm",
      edition: "1/1 - Pezzo Unico",
      tags: ["tane", "foresta", "mitologia", "foglie", "dio"],
      likes: 245,
      views: 2891,
    },
    {
      id: "SPR25-012",
      title: "Puāwai o te Ao",
      artist: "Hinemoana Raukura",
      price: 45,
      owner: "Certificato Originale",
      collection: "Estate 2025",
      description: "Fioritura del mondo — un'opera che celebra la bellezza delle piante che sbocciano in armonia con la natura.",
      status: "sold",
      image: "https://images.unsplash.com/photo-1590235913215-c52fffb2f3f0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      sealDate: "20 Marzo 2025",
      materials: "Cartoncino - dipinta a mano",
      dimensions: "63 mm x 88 mm",
      edition: "1/1 - Pezzo Unico",
      tags: ["fioritura", "mondo", "piante", "armonia", "natura"],
      likes: 167,
      views: 1923,
    },
    {
      id: "SPR25-018",
      title: "Rautipu Aroha",
      artist: "Rongo Pikiatua",
      price: 45,
      owner: "Certificato Originale",
      collection: "Estate 2025",
      description: "Foglie intrecciate d'amore — ispirato all'arte dell'intreccio con le foglie di harakeke (flax).",
      status: "sold",
      image: "https://images.unsplash.com/photo-1727525895934-ae4350538c59?q=80&w=1012&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      sealDate: "28 Marzo 2025",
      materials: "Cartoncino - dipinta a mano",
      dimensions: "63 mm x 88 mm",
      edition: "1/1 - Pezzo Unico",
      tags: ["intreccio", "amore", "harakeke", "flax", "tradizionale"],
      likes: 198,
      views: 2456,
    },
  ]

// come ritorno questo array per usarlo in tutte le pagine che lo richiedono?
export default artworks;